pool:
  name: Azure Pipelines
steps:
- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'

- script: |
   docker run --rm \
      -e NEOLOAD_PROJECT_URL=https://github.com/22INF3B6/TricentisWebshop/blob/main/TricentisWebshop.zip \
      -e SCENARIO_NAME=scenario1 \
      -e NEOLOADWEB_TOKEN=1f06e59572b75d60417b5215ad9abfa43768b6508ddccb8c \
      -e TEST_RESULT_NAME=GetPaymentMethodCollection \
      -e CONTROLLER_ZONE_ID=localhost \
       -e LG_ZONE_IDS=localhost:7100 \
      neotys/neoload-web-test-launcher:latest
   
  displayName: 'Launch NeoLoad test'