pool:
  name: Azure Pipelines
steps:
- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'

- script: |
   docker run --rm \
      -v "$(Build.Repository.LocalPath)":https://github.com/22INF3B6/TricentisWebshop.git \
      -e SCENARIO_NAME=scenario1 \
      -e NEOLOADWEB_TOKEN=1f06e59572b75d60417b5215ad9abfa43768b6508ddccb8c \
      -e TEST_NAME=CI-TestGetPaymentMethodCollection \
      -e CONTROLLER_ZONE_ID=Default zone  \
      -e LG_ZONE_IDS=defaultzone:<LG count#1> \
      neotys/neoload-web-test-launcher:latest
   
  displayName: 'Launch NeoLoad test'